<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SocialLoginFree
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

//$meggalifeUrl = "https://dev.meggalife.com/";
$meggalifeUrl = $this->helper('Meggalife\Auth\Helper\Data')->getConfig('meggalife_auth/general/base_url');
?>

<div class="block block-customer-login">
<!--    <div class="block-title">-->
<!--        <strong id="block-customer-login-heading" role="heading" aria-level="2">--><?php //echo $block->escapeHtml(__('Registered Customers Heres')) ?><!--</strong>-->
<!--    </div>-->
    <div class="block-content" aria-labelledby="block-customer-login-heading">
<!--        <form class="form form-login"-->
<!--              action="--><?php //echo $block->escapeUrl($block->getPostActionUrl()) ?><!--"-->
<!--              method="post"-->
<!--              id="login-form"-->
<!--              data-mage-init='{"validation":{}}'>-->
<!--            --><?php //echo $block->getBlockHtml('formkey') ?>
<!--            <fieldset class="fieldset login" data-hasrequired="--><?php //echo $block->escapeHtml(__('* Required Fields')) ?><!--">-->
<!--                <div class="field note">--><?php //echo $block->escapeHtml(__('If you have an account, sign in with your email 888888888888888.')) ?><!--</div>-->
<!--                <div class="field email required">-->
<!--                    <label class="label" for="email"><span>--><?php //echo $block->escapeHtml(__('Email')) ?><!--</span></label>-->
<!--                    <div class="control">-->
<!--                        <input name="login[username]" value="--><?php //echo $block->escapeHtml($block->getUsername()) ?><!--" --><?php //if ($block->isAutocompleteDisabled()): ?><!-- autocomplete="off"--><?php //endif; ?><!-- id="email" type="email" class="input-text" title="--><?php //echo $block->escapeHtml(__('Email')) ?><!--" data-validate="{required:true, 'validate-email':true}">-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="field password required">-->
<!--                    <label for="pass" class="label"><span>--><?php //echo $block->escapeHtml(__('Password')) ?><!--</span></label>-->
<!--                    <div class="control">-->
<!--                        <input name="login[password]" type="password" --><?php //if ($block->isAutocompleteDisabled()): ?><!-- autocomplete="off"--><?php //endif; ?><!-- class="input-text" id="pass" title="--><?php //echo $block->escapeHtml(__('Password')) ?><!--" data-validate="{required:true}">-->
<!--                    </div>-->
<!--                </div>-->
<!--                --><?php //echo $block->getChildHtml('form_additional_info') ?>
<!--                <div class="actions-toolbar">-->
<!--                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span>--><?php //echo $block->escapeHtml(__('Sign In')) ?><!--</span></button></div>-->
<!--                    <div class="secondary"><a class="action remind" href="--><?php //echo $block->escapeUrl($block->getForgotPasswordUrl()) ?><!--"><span>--><?php //echo $block->escapeHtml(__('Forgot Your Password?')) ?><!--</span></a></div>-->
<!--                </div>-->
<!---->
<!--                --><?php
//                //$helper = $this->helper('Plumrocket\SocialLoginFree\Helper\Data');
//                ?>
<!--            </fieldset>-->
<!--        </form>-->
<!--        <div class="primary"><button type="button" class="action login primary" name="meggalogin"   id="megga"><span>--><?php //echo $block->escapeHtml(__('Login With Meggalife'))?><!--</span></button></div>-->

    </div>

    <div id="modal-form" style="display: none">
        <div class="meggalife-iframe">
            <iframe  width="100%" height="600" id="megga-login-iframe" data-src="<?php echo $meggalifeUrl?>ipseserver/authorize/client_id/meggamore@client/response_type/code/grant_type/authorization_code/state/session" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
    <a class="action open-modal-form login primary"
       href="#"
       title="Login with Meggalife">
    <span><?php echo $block->escapeHtml(__('Login With Meggalife'))?></span>
    </a>
    <a class="action signup primary"
       href=<?php echo $meggalifeUrl."signup" ?>
       title="Signup with Meggalife">
        <span><?php echo $block->escapeHtml(__('Signup With Meggalife'))?></span>
    </a>
    <script type="text/x-magento-init">
        {
            ".open-modal-form": {
                "Meggalife_Auth/js/modal-form": {}
            }
        }
    </script>
</div>

