<fieldset class="fieldset create account" data-hasrequired="<?php echo __('* Required Fields') ?>">
	<legend class="legend"><span><?php echo __('Additional Information') ?></span></legend><br>
	<div class="field my_attribute required">
    	<label for="mobilenumber" class="label"><span><?php echo __('Mobile Number') ?></span></label>
            <div class="control">
                <input type="text" name="mobilenumber" id="mobilenumber" title="<?php echo __('Mobile Number') ?>" class="input-text" data-validate="{required:true}" autocomplete="off" required>
            </div>
     </div>
</fieldset>
