<?php 
$formurl = $block->getUrl('registration/index/verifyotp');
?>

<form class="form create account form-create-account" action="<?php echo $formurl?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
	<fieldset class="fieldset create account" data-hasrequired="<?php echo __('* Required Fields') ?>">
		<div class="field my_attribute required">
	    	<label for="mobilenumber" class="label"><span><?php echo __('OTP') ?></span></label>
	            <div class="control">
	                <input type="text" name="otpnumber" id="otpnumber" title="<?php echo __('OTP') ?>" class="input-text" data-validate="{required:true}" autocomplete="off">
	            </div>
	     </div>
	</fieldset>
	<div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Verify OTP') ?>"><span><?php /* @escapeNotVerified */ echo __('Verify OTP') ?></span></button>
        </div>
    </div>
</form>
