<?php
	$isEnable = $this->helper('Ipragmatech\Bannerblock\Helper\Data')->getConfig('bannerblocksection/general/banneractive');
	$selectedCategoriesId = $this->helper('Ipragmatech\Bannerblock\Helper\Data')->getConfig('bannerblocksection/bannerblock_setting/bannerlist');
	$canshowImg = $this->helper('Ipragmatech\Bannerblock\Helper\Data')->getConfig('bannerblocksection/bannerblock_setting/showimage');;
	$categoryids = (explode(',',$selectedCategoriesId));
?>
<?php if($isEnable):?>
<div class="category-list-widget">
	<?php if(count($categoryids)):?>
		<?php foreach ($categoryids as $cid):?>
			<div class="category-container-widget">
				<?php $rootCategory = $this->getCategorymodel($cid); ?>
				<div class="category-heding-widget">
			        	<a href="<?php echo $rootCategory->getUrl(); ?>" >
			        		<?php if($canshowImg && $rootCategory->getImageUrl()):?>
			        			<img alt="" width="100%" height="100px" src="<?php echo $rootCategory->getImageUrl() ?>"/>
			        			<span class="content bg-white">
						               <strong class="title">Now Shop by category</strong><br />
						               <span class="info"><?php echo $rootCategory->getName(); ?></nobr> collection</span>
						         </span>
						       <div class="content-heading">
							       <p class="info">More in <?php echo $rootCategory->getName(); ?></p>
							 </div>
			        		<?php else:?>
				        		<div class="content-heading">
							       <h2 class="title"><?php echo $rootCategory->getName(); ?></h2>
							    </div>
			        		<?php endif;?>
			        	</a>
		       	 </div>
		       	 <div class="subcategory-container-widget">
		       	 	<!-- sub category section -->
		       	 	<?php $subcategories = $this->getChildCategories($rootCategory)?>
		       	 	<?php if($subcategories): ?>
		       	 		<div class="products-grid grid">
        					<ol class="product-items widget-product-grid">
			       	 	<?php foreach ($subcategories as $subcategoryId) : ?>
			       	 	<?php $subcategory = $this->getCategorymodel($subcategoryId); ?>
			       	 		<li class="product-item" style="width:250px;  padding-left:30px;">
				       	 		 <div class="product-item-info">
				       	 			<span>
				       	 				<a href="<?php echo $subcategory->getUrl(); ?>">
							        		<?php if($canshowImg && $subcategory->getImageUrl()):?>
							        			<img class="sub-cat-image" alt=""  src="<?php echo $subcategory->getImageUrl() ?>" width="240" height="300"/>
							        		<?php endif;?><br/>
							        		<span class="cat-title"><?php echo $subcategory->getName(); ?></span>
							        	</a>
				       	 			</span>
				       	 		</div>
			       	 		</li>
			       	 	<?php endforeach;?>
			       	 	</ol>
			       	 	</div>
		       	 	<?php endif;?>
		       	 </div>
	       	</div>
		<?php endforeach;?>
	<?php endif;?>
</div>
<?php endif;?>